name: Unit Tests (regexp_extract)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  regexp-extract-unit:
    name: Run regexp_extract Unit Tests
    runs-on: ubuntu-latest

    env:
      RUST_BACKTRACE: full

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: stable

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev cmake clang

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache target dir
      uses: actions/cache@v3
      with:
        path: |
          target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Run unit tests for regexp_extract
      run: cargo test -p datafusion-physical-expr regexp_extract
